### ISSUE TITLE
Create a new branch for DATM

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/NEMSdatm#13]
In this new branch, the data atmosphere model code will be modified to add air-sea flux calculations. The SST field from the mediator will be used to compute new fluxes.

The modified data atmosphere model will also need 10-m winds as input fields.

**Comment by DeniseWorthen** [comment]
The DATM currently imports no fields from the mediator. The only way to accomplish this is to add back the importstate to the datm, along with a prep_atm run phase. Is that what you intend to do?

**Comment by binli2337** [comment]
Yes.

**Comment by DeniseWorthen** [comment]
I think it makes a lot more sense to move this calculation to the mediator rather than add that amount of complexity back to the DATM. All you would need is to have DATM export u10m, v10m in addition to the the other fields and then add a custom calculation in prep ocean.

**Comment by DeniseWorthen** [comment]
@junwang-noaa @jkbk2004

I still don't understand the reasoning here. If the purpose is to use bulk-formula calculations of surface fluxes for the ocean, that is already being done in the module_Methods. The calculation there uses the Large & Yeager formulas for fluxes. 

These fields are available in the aoflux field bundle. Currently we are using these aofluxes in the prep_ocn phase only on icy points; however the prep_ocn phase could be modified to use the ao-flux calculations on all water points.

I don't understand why we would want to have the DATM import the SST just do do a calculation that is already available.

**Comment by junwang-noaa** [comment]
Denise,

The idea is to get sst from ocean and to use that sst as input to bull
formula to constrain the atmosphere fluxes. Current issue is that the
fluxes are completely from CFSR, if the forcing is not compatible to what
MOM6 expected, there is no adjust to the CFSR forcing

**Comment by hyunchul386** [comment]
@DeniseWorthen 

The purpose of using bulk-formula here, is to use the SST fields of MOM6, of which heat fluxes are consistent with the ocean. The bulk formula will be based on Large et al. and Large & Yeager (2004).

Question is whether the bulk formula in the model_Methods uses the SST from MOM6 or not.
If yes, is the SST of ocean updated with time?
If no, what is the SST?

**Comment by DeniseWorthen** [comment]
The SST that the aoflux calculation uses is from the ocean. It is taken from the FBOcn_o field bundle [here](https://github.com/NOAA-EMC/NEMS/blob/cec5a083b87dc37358eade618bf8a0a461408957/src/module_MEDIATOR.F90#L5092).

It will be updated as often as the Ocean itself updates the field.

**Comment by hyunchul386** [comment]
It sounds great for me.
The aoflux is including recalculated fluxes, like Qe, Qh, Qb,   is it correct?

**Comment by DeniseWorthen** [comment]
I'm not sure what you are referring to as Qe, Qh and Qb. The resultant fluxes from the aoflux calculation are just below the line I linked to, following this line: !--- atm/ocn fluxes output

**Comment by hyunchul386** [comment]
My understanding is that currently, bulk formula fluxes of aoflux are using on ice point and
can be extended to all water points. It is correct, would you let me know how to extend
aoflux to all grids?

**Comment by junwang-noaa** [comment]
Bin is working on bringing the SST back, currently DATM does not have
import state to get any fields from the mediator where OCN sst is available.

**Comment by DeniseWorthen** [comment]
To use the aoflux fields for all points (icy and non-icy) the custom merges in the prep_ocn phase will need to be modified.

**Comment by hyunchul386** [comment]
In the MEDIATOR, where is the fluxes of the bulk formula calculated?

**Comment by DeniseWorthen** [comment]
look in module_MEDIATOR_methods.F90

**Comment by hyunchul386** [comment]
Thanks, and one thing is
in line 155 of  module_MEDIATOR_methods.F90, qsat(Tk) is defined as
qsat(Tk)   = 640380.0_R8 / exp(5107.4_R8/Tk)
and according to Large and Yeager, it seems that
qsat(Tk)   = alpah * 640380.0_R8 / exp(-5107.4_R8/Tk)
 
1) On -5170/5170, is it compensated somewhere?
2) The alpha would be 0.98 over the water and 1.0 elsewhere.

**Comment by DeniseWorthen** [comment]
Is delq calculated in the same direction? 

Here, delq = qbot (this is the atm) - ssq (this is qsat).

**Comment by hyunchul386** [comment]
ssq is multiplied by 0.98 from qsat and delq should be the difference, for
me it looks correct.
It seems that "-5107.4" is inside an exponential.
